PRODUCT_VERSION_MAJOR = 20
PRODUCT_VERSION_MINOR = 0
LINEAGE_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)
LINEAGE_BUILDTYPE := FE

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)-$(LINEAGE_ZIP_TYPE)-$(LINEAGE_BUILD)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)
